stages:
  - lint
  - test

linting:
  stage: lint
  image: node:16-alpine
  before_script:
    - npm ci
    - npm run format
  script:
    - npm run lint
  only:
    - pushes

testing:
  stage: test
  image: node:16-alpine
  before_script:
    - npm ci
  script:
    - npm run test
  only:
    - merge_requests
  dependencies:
    - linting