### User Registration ###

POST http://localhost:5000/api/auth/signup
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "johndoe@example.com",
  "password": "password123"
  
}
### User Login ###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "password123"
}