
GET http://localhost:5000/api/private
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTY4OTE0NTY2OCwiZXhwIjoxNjg5MTQ5MjY4fQ.BCuHedSzSolykJDuVxY5rUV4otwNZzDbo_uJCHcHdNU